### ISSUE TITLE
Remove endpoint `/assets` and `/assets/ddo`

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#535]
Linked issues:
https://github.com/oceanprotocol/market/issues/719
https://github.com/oceanprotocol/aquarius/issues/526

**Comment by TimDaub** [comment]
>     * https://app.zenhub.com/workspaces/frontend-60acd67b133a660014278212/issues/oceanprotocol/market/719
> 
>     * https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/526

these issues cannot be accessed from external users. Why is there a plan to remove this endpoint?

**Comment by mihaisc** [comment]
@TimDaub i updated the links with the github equivalent

**Comment by TimDaub** [comment]
Thanks, and I imagine that `/api/v1/aquarius/assets` is anyways an outdated endpoint as I can't see it in the reference docs anymore, right? https://docs.oceanprotocol.com/references/aquarius/

**Comment by mihaisc** [comment]
They are the first 2 endpoints, ignore the `/api/v1/` portion

**Comment by TimDaub** [comment]
Really? Why are they removed? I'm using them in production. What is recommended to be used instead? Why is none of this ever communicated to users of Aquarius?

**Comment by DMats** [comment]
@TimDaub Thank you for your questions.

>Why are [the `/assets` and `/assets/ddo` endpoints] removed?

Unfortunately, the `/assets` and `/assets/ddo` endpoints are currently broken on Rinkeby because it contains more than 10,000 assets. It's expected that other chains will suffer the same issue, left unchecked. The prospect of implementing [deep pagination](https://discuss.elastic.co/t/pulling-more-than-10000-records-from-elasticsearch-query/181000/2) was briefly evaluated but ultimately rejected on the basis that
1. it would be difficult to implement
2. Unconstrained queries like "all assets" or "all asset DDOs" had low utility
3. It is unlikely that Aquarius users were using them

> I'm using them in production.

Clearly, our assumption (3) was incorrect based on your assertion. Nonetheless, the current plan is to proceed with the removal because the `/assets` and `/assets/ddo` functionality can still be achieved as described below.

> What is recommended to be used instead?

To replace the `/assets` functionality, query the list of datatoken addresses from our subgraph and prepend `did:op:` to each address.

To replace the `/assets/ddo` functionality, query the list of datatoken addresses from our subgraph, prepend `did:op` to each address, and then query the DDOs from aquarius, one-by-one

**Comment by kremalicious** [comment]
> Really? Why are they removed? I'm using them in production. What is recommended to be used instead?

What you are using in production is an endpoint to get all assets of ETH mainnet. I would suggest you replace this  with Aquarius v3.0.0+ with a `/ddo/query` search query for all assets in all production chains instead (hint: possible right now with `aquarius.oceanprotocol.com`). 

Showing all assets of all networks including test networks by default is simply not useful and makes us run too much into above mentioned restrictions. So we are asking to replace them with specific queries for specific networks instead as I'm sure you are only interested in chains with actual value.

> Why is none of this ever communicated to users of Aquarius?

point taken, existing integrations were considered too but development is faster than explaining blog post. There's a draft blog post for introducing multi network with a specific migration part for Aquarius v3.0.0 and how we deal with existing remote deployments of Aquarius. This should make things more clear then but the gist is that if you use the remote deployments like `aquarius.mainnet...` they will stay as is and won't be updated so no external tools using them right now will break.
