### ISSUE TITLE
Aquarius data structure is unclear to external users

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/aquarius#538]
It's unclear what data structure Aquarius is currently delivering to users. For external users like me, this is particularly problematic, as I'm relying on this part of the infrastructure. The docs don't state it. I haven't found anything in this repo either and the endpoint running in production e.g. returns weird values for `[].price`: https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo

Is there any document that outlines what can be relied upon wrt to the data structure to make it possible for external users (non-OPF employees) to use Aquarius?

**Comment by trentmc** [comment]
I believe the structure that this issue is looking for is at:
- https://docs.oceanprotocol.com/concepts/did-ddo/
- https://docs.oceanprotocol.com/concepts/ddo-metadata/

This content was recently ported from the oep repo, by Akshay. Then cleaned up suitable for docs.

Therefore the only remaining thing for this issue, it seems, is : if possible point to the links above from the aqua documentation.

**Comment by calina-c** [comment]
v3.0.2 will have links to the DID/DDO and DDO metadata references. It is now currently being tested by the frontend team, but we will release sometime this week. Until then I'm putting this in the review column.
