### ISSUE TITLE
Remove v1 from the base endpoint

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#547]

**Comment by DMats** [comment]
Should this task include removing `/api/v1` or even `/api/v1/aquarius` instead of just `/v1`? I think removing `/api/v1/aquarius would be okay. What does everyone else think?

**Comment by trentmc** [comment]
The motivation for "v1" was so that we could upgrade to other versions and change the interface. 

In practice, we have upgraded Aquarius fuctionality with breaking changes to the api, without changing from "v1". (Bad practice)

Why isn't the best way forward the following: _do_ retain the "vx" interface and actually _use_ it when we do breaking changes to the api?

**Comment by AnaLoznianu** [comment]
@alexcos20 Can you give some context for this issue?

**Comment by trentmc** [comment]
Update: today in BE core planning, we discussed the pros & cons whether "v1".

Realization: there's a difference between a REST API that (a) an org only really uses internally, versus (b) a REST API that is meant to be consumed by >>1 external parties. 
- (a) doesn't need "v1"; (b) does.
- Aquarius is (a). Which means we don't need "v1". Which means we _should_ proceed with deprecating "v1", ie the aim of this issue.
