### ISSUE TITLE
Docs on running for multiple chains are very limited

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/aquarius#561]
The current README block on [running Aquarius for multiple chains](https://github.com/oceanprotocol/aquarius#running-aquarius-for-multiple-chains) should be improved with clear code examples and examples for all those mentioned env vars. Like, impossible to know what `NETWORK_NAME` should be unless I dig deep in the code to see how we named the networks.

There should be examples for running Aquarius against our current mainnets, which is ETH Mainnet, Polygon, BSC. If space is limited and we want to say a lot, then we can do a tutorial in the docs instead.

**Comment by md00ux** [comment]
@kremalicious, we have a step-by-step guide here with examples here: 
https://github.com/oceanprotocol/aquarius/tree/main/deployment
It could be improved, although I have removed some of the previously written information to reduce the size.
Please take a look and suggest any improvements that can be added to bring more clarity.
It's not in the main README, it could be linked.

**Comment by trentmc** [comment]
Update: @calina-c has added some basic documentation on multi-chain in her PR for aqua #563, updating the main README. https://github.com/oceanprotocol/aquarius/pull/564

The md linked by @md00ux is much more detailed. 

All other md files should be linked from the main README. Otherwise it's much harder to discover, definitely not obvious.

My suggestion for this issue: in the main README in Calina's new section on multichain, add a sentence "details for xx yyy are here" and point to https://github.com/oceanprotocol/aquarius/tree/main/deployment.

**Comment by calina-c** [comment]
Will do.
