### ISSUE TITLE
Query with filters on aquarius are not working

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#693]
- [ ] Filter by id is not working: https://github.com/oceanprotocol/market/issues/1052#issuecomment-1031702296

TODO: Add the list of all queries that are not working

**Comment by claudiaHash** [comment]
Hi, 
@bogdanfazakas and I also tested this on market and seems like: 

- searching by id currently works but only if you get rid of the `did:op:` prefix : 
![Screenshot from 2022-02-08 14-09-30](https://user-images.githubusercontent.com/49017601/153156629-db8065e2-1eee-40b7-ba9e-7f1ae9a634e6.png)

- 'No mapping found for [metadata.created] in order to sort on' error appears at some points
