### ISSUE TITLE
Add validation proof on aquarius

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/aquarius#813]
Linked Smart contracts functionality: https://github.com/oceanprotocol/contracts/blob/v4main/contracts/templates/ERC721Template.sol#L279-L292

This is for the isolated marketplace feature

**Comment by alexcos20** [comment]
In order to run an isolated market, the following flow should be applied:
 - create the ddo in market/ocean lib, etc
 - call one or more aquarius validate endpoints, which will return a json object if ddo is valid
 ```
{"hash": "xxxx", "publicKey": "0x32434", "r": "xxx", "s": "xxx", "v": "xxx"}
```
- when publishing the metadata (https://github.com/oceanprotocol/contracts/blob/v4main/contracts/templates/ERC721Template.sol#L228-L256) user can add validationProofs  (means the ddo was validate by aquarius instance X)

On Aquarius side:
 - have a env called  ALLOWED_VALIDATORS
 - if that array is not empty, check if any of the public addresses in every proof event is included in ALLOWED_VALIDATORS.
 - - if yes, cache the ddo
 - - if not, reject the ddo

**Comment by alexcos20** [comment]
Let's assume:
  - Aquarius A  has a list of allowed_validators (only A's address)
  - Aquarius B  has a list of allowed_validators (only B's address)
  - Aquarius C  has a list of allowed_validators (A's + B's + C's addresses)
  - Aquarius D has no list of allowed_validators

We have the following scenarios:

 - new asset is published with A's proof -> A will cache, B will ignore, C will cache, D will cache
 - asset is updated:
  - - only A proof is added -> A will cache, B will skip, C will cache, D will cache
  - - both A+B proofs are added -> A will cache, B will cache, C will cache, D will cache
  - - only B proof is added -> A will drop existing cache, B will cache, C will cache, D will cache
