### ISSUE TITLE
Chain list seems to be wrong

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#852]
https://v4.aquarius.oceanprotocol.com/api/aquarius/chains/list reports only two chains.

**Comment by calina-c** [comment]
I spent the morning investigating this. A restart of the events monitor fixed everything.

I think the culprit is this generic Exception handling here:
![Screenshot 2022-07-15 at 10.26.08.png](https://images.zenhubusercontent.com/5795cf04e40e5714b16c76c5/31102e5e-e56e-4928-8fb4-85d2df2f2db8)

However, I am unsure whether this was a correct flow, a random/byzantine exception, issues with ES or something else. The logic does not seem flawed but in extreme cases it might prove to be a problem. However, finding out the exact, specific Exception that happened here is a bit overkill this time.

I propose closing this ticket and monitoring the chains for other inconsistencies in the future. If it happens again, the information is here and we can spend more time debugging.
