### ISSUE TITLE
Aquarius fails to index some ddos

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#994]
While trying to move aqua to graviton ( arm cpu) i discovered there were multiple ddos that were not being indexed, on test networks there were ~200 and relative few on mainnets . It is normal to have some assets not indexed due to various reasons. At least the ones bellow have no reason to not be indexed 

did:op:4202fc033fe6787e75cf641e8893e4676dfbff54233c8352ab73bb16efb09589
did:op:26d135e61d885dd0c477e99796d4ee4a0b33991071a1f753db6a6566263fcaf7
did:op:65e051b2d4e6d5053b021a0bb1d1699d0cf16c628559f0c111d090535bba50d6

These are on polygon

**Comment by trentmc** [comment]
Maria: investigated this yesterday. Talked to Mihai S. Mihai S will have Marian put Aquarius onto Graviton.

Alex: this won't work, because Graviton uses ARM cpus, and Aquarius Docker images are intel x86/64 CPUs

Alex: to solve, we need a new instance of Aquarius, and see how well it does.

--
T: why was Mihai S trying to move to Graviton in the first place?

Ana: cost, I think

Alex: likely true, since ARM CPUs are way cheaper.

**Comment by trentmc** [comment]
Related: https://github.com/oceanprotocol/pm/issues/191 "Docker images for multiple platforms"

--
Text from that ticket, copied here for convenience:
--
All of our docker images are built using x86_64.   
But lately, we see more and more users trying to run either barge, either stand alone components on other platforms

Proposal:
 - when building our images, make sure we support all of:
 ```
 Architectures officially supported by Docker, Inc. for running Docker: (see [download.docker.com](https://download.docker.com/linux/))
ARMv6 32-bit (arm32v6): https://hub.docker.com/u/arm32v6/
ARMv7 32-bit (arm32v7): https://hub.docker.com/u/arm32v7/
ARMv8 64-bit (arm64v8): https://hub.docker.com/u/arm64v8/
Linux x86-64 (amd64): https://hub.docker.com/u/amd64/
Windows x86-64 (windows-amd64): https://hub.docker.com/u/winamd64/
```


This has to cover all of our images (contracts, aqua, provider, c2d, rbac, etc)

**Comment by alexcos20** [comment]
Re-opening, because we have more context:

- Aquarius was running on x86_64, only elasticseach was using ARM (and elasticsearch has support for ARM)
- when indexing polygon, aqua indexed a lot of assets, but there is no exact copy between those two aqua instances
We should have the same assets in both aqua instances, because source of truth is blockchain.
This means that Aquarius has a bug.

**Comment by mihaisc** [comment]
Old issue, didn't receive any other similar bugs, maybe it was an issue when debugging.
